export { default as BLOGS_PALACE } from './palace.jpg'
export { default as BLOGS_PALACE_1 } from './palace.jpg'
export { default as BLOGS_PALACE_2 } from './palace.jpg'
export { default as BLOGS_PALACE_3 } from './palace.jpg'
export { default as BLOGS_PALACE_4 } from './palace.jpg'
export { default as BLOGS_PALACE_5 } from './palace.jpg'
